version resolved to use data in Marker for flutter_map
Xennis/flutter_map_location pull request #82
Opened 2021-08-21 11:33 UTC by sandeshgyw

2021-08-21 12:13 UTC, xni06 commented on pubspec.yaml
> +      url: "https://github.com/sandeshgyw/flutter_map.git"
Could you achieve the same result my using the released version of `flutter_map_location` but override the `flutter_map` using `depencency_override` in your app's `pubspec.yaml`?

2021-08-22 10:17 UTC, xni06 commented
@sandeshgyw it is safe to close/cancel this PR as it has been resolved another way - thanks.

2021-08-22 18:25 UTC, Xennis commented on pubspec.yaml
> +      ref: "13db571"
Please don't add unpublished Dart packages here. Let's use the official flutter_map.

You can't publish a Dart packages build on top of unpublished repos/packages.

2021-08-22 18:25 UTC, Xennis commented on example/ios/Podfile
> +# Uncomment this line to define a global platform for your project
Dear @sandeshgyw can you please provide some information on what that codes here is based?

2021-08-22 18:26 UTC, Xennis requested changes
See comments above

2021-08-23 12:37 UTC, closed without merging